name = "researchroomies"
main = "src/index.ts"
compatibility_date = "2025-08-26"

[observability]
enabled = true

[assets]
directory = "./public/"
not_found_handling = "404-page"
binding = "ASSETS"
run_worker_first = [ "/api/*" ]

[[routes]]
pattern = "researchroomies.com"
custom_domain = true