-- Baseline: production as it stood before migrations existed.
--
-- Every statement is idempotent, because this file has to run against two very
-- different databases and reach the same place:
--
--   * production, which already has all of it — here the whole file is a no-op,
--     and its only job is to let wrangler record 0001 as applied so that 0002
--     onward line up;
--   * a fresh database (local dev, the test suite), which gets the real thing.
--
-- Do not edit this file to add a table or change a seed. That is what put the
-- tag list out of step with production in the first place: `INSERT OR IGNORE`
-- is idempotent for *creation* and silently a no-op for *change*, so editing a
-- seed row here and re-running changes new databases and leaves old ones alone.
-- Every change after this point gets its own numbered migration.

CREATE TABLE IF NOT EXISTS countries (
    id INTEGER NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    iso2 TEXT,
    iso3 TEXT
);

CREATE TABLE IF NOT EXISTS states (
    id INTEGER NOT NULL PRIMARY KEY,
    country_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    code TEXT,
    FOREIGN KEY (country_id) REFERENCES countries(id)
);

CREATE TABLE IF NOT EXISTS cities (
    id INTEGER NOT NULL PRIMARY KEY,
    country_id INTEGER,
    state_id INTEGER,
    name TEXT NOT NULL,
    FOREIGN KEY (country_id) REFERENCES countries(id),
    FOREIGN KEY (state_id) REFERENCES states(id)
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER NOT NULL PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    created_at INTEGER,
    last_login_at INTEGER
);

CREATE TABLE IF NOT EXISTS conferences (
    id INTEGER NOT NULL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    location_address TEXT,
    city_id INTEGER,
    start_time INTEGER NOT NULL,
    stop_time INTEGER NOT NULL,
    description TEXT,
    created_at INTEGER,
    is_featured INTEGER DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (city_id) REFERENCES cities(id)
);

CREATE TABLE IF NOT EXISTS posts (
    id INTEGER NOT NULL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    conference_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (conference_id) REFERENCES conferences(id)
);

CREATE TABLE IF NOT EXISTS flags (
    id INTEGER NOT NULL PRIMARY KEY,
    post_id INTEGER NOT NULL,
    reason TEXT,
    flagged_by TEXT,
    timestamp INTEGER,
    FOREIGN KEY (post_id) REFERENCES posts(id)
);

CREATE TABLE IF NOT EXISTS tags (
    slug TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS conference_tags (
    tag_slug TEXT NOT NULL,
    conference_id INTEGER NOT NULL,
    PRIMARY KEY (tag_slug, conference_id),
    FOREIGN KEY (tag_slug) REFERENCES tags(slug),
    FOREIGN KEY (conference_id) REFERENCES conferences(id)
);

CREATE TABLE IF NOT EXISTS message (
    post_id NUMBER,
    sender_email STRING,
    recipient_email STRING,
    content STRING,
    timestamp NUMBER
);

-- Conference slugs address /conference/:slug, so collisions make a conference
-- unreachable. reserveSlug() in src/db/conferences.ts suffixes duplicates;
-- this index is the backstop.
CREATE UNIQUE INDEX IF NOT EXISTS idx_conferences_slug ON conferences(slug);

CREATE INDEX IF NOT EXISTS idx_posts_conference_id ON posts(conference_id);
CREATE INDEX IF NOT EXISTS idx_posts_user_id ON posts(user_id);
CREATE INDEX IF NOT EXISTS idx_flags_post_id ON flags(post_id);

-- The subject list *as production actually carries it*: five short slugs, not
-- the twelve long ones the old db/schema.sql seeded. This is the drift, written
-- down rather than papered over, so that 0002 is a real change with the same
-- effect on every database rather than a seed that only new ones ever see.
--
-- The names here are a reconstruction — production's rows were never read back
-- into version control. That is safe: 0002 upserts all twelve names explicitly,
-- so whatever these say (and whatever production says) is overwritten with the
-- canonical value one migration later.
INSERT OR IGNORE INTO tags (slug, name) VALUES
    ('math', 'Mathematics'),
    ('physics', 'Physics'),
    ('chem', 'Chemistry'),
    ('bio', 'Biology'),
    ('cs', 'Computer Science');
